### ISSUE TITLE
Beautify the home page and all other pages using CSS

### ISSUE THREAD

**Issue by asmit203** [asmit203/TalkitOut#15]
Beautify the home page and all other pages using CSS

**Comment by pundarikaksha7** [comment]
Kindly assign me this issue

**Comment by iamatifmoin** [comment]
@asmit203 
Please assign it to me if no one is working on it.

**Comment by iamatifmoin** [comment]
Working on it!

**Comment by Albert-2** [comment]
hey @asmit203
I would like to contribute to this issue as I am quite good at responsive designs and frontend  
Can you please assign me the issue
THANK YOU FOR CONSIDERING...... :)

**Comment by asmit203** [comment]
@Albert-2 Assigned

**Comment by Albert-2** [comment]
hey @asmit203

**Comment by Albert-2** [comment]
hey @asmit203 
The issue said "Beautify the home page and all other pages using CSS" 
Please correct me if i am wrong but there is no homepage and css to beautify
what  actually am i supposed to do create a new home page from scratch? or i missed something....?

**Comment by asmit203** [comment]
> hey @asmit203 The issue said "Beautify the home page and all other pages using CSS" Please correct me if i am wrong but there is no homepage and css to beautify what actually am i supposed to do create a new home page from scratch? or i missed something....?

Ho e page is referring to the base html and base css you can create your own base template also

**Comment by Albert-2** [comment]
ok....

**Comment by HemantKumar01** [comment]
if @Albert-2 is not working on it, can i get assigned.

**Comment by Albert-2** [comment]
hey @asmit203 
assign it to @HemantKumar01 I'm travelling so nit able to work on it sorry for inconvenience
hope you will cooperate
Thank you

**Comment by asmit203** [comment]
@HemantKumar01 the file upload page is not beautified please look into that too

**Comment by HemantKumar01** [comment]
done

https://github.com/asmit203/TalkitOut/assets/71439585/c3c0dd87-8f81-46f4-bc20-db39b6c99b5b
