### ISSUE TITLE
reformat readme file

### ISSUE THREAD

**Issue by chandansgowda** [asmit203/TalkitOut#35]
The readme file looks plain and also contains `</br>` in between the commands to be executed to setup the environment. It has to be correctly formatted.
<img width="866" alt="Screenshot 2022-12-08 at 7 17 23 PM" src="https://user-images.githubusercontent.com/41890434/206462532-8c375ac6-4ff7-46dc-b30a-d439de198def.png">

**Comment by nik132-eng** [comment]
can you assign me this issue?
