### ISSUE TITLE
Convert the HTML files for the frontend : Subapp - blog

### ISSUE THREAD

**Issue by asmit203** [asmit203/TalkitOut#37]
Convert the HTML files for the frontend : Subapp - blog 

The html file contains jinja code use the basic html and then use js to replace those jinja code to work with the rest api's

- [x] favourites.html (10 pts)
- [x] announcement.html (10 pts) 
- [x] post_form.html (10 pts)
- [x] base.html (20 pts)
- [x] home.html (20 pts)
- [x] post_confirm_delete.html (20 pts)
- [x] post_detail.html (20 pts)
- [x] post_list.html (20 pts)
- [x] upvotedposts.html (20 pts)
- [x] user_posts.html (20 pts)

**Comment by HemantKumar01** [comment]
Please assign me this issue. Already working on it.
i am converting to react currently, should i convert to basic html+js instead?

**Comment by asmit203** [comment]
> Please assign me this issue. Already working on it. i am converting to react currently, should i convert to basic html+js instead?

as you wish you can keep the html as it is and update for jinja only or can update both as you wish.

**Comment by asmit203** [comment]
Completed
