### ISSUE TITLE
make the rest api handling subapp

### ISSUE THREAD

**Issue by asmit203** [asmit203/TalkitOut#39]

**Comment by Mayank77maruti** [comment]
Hey @asmit203 , can you please assign this task to me.

**Comment by asmit203** [comment]
> Hey @asmit203 , can you please assign this task to me.

ok assigned

**Comment by asmit203** [comment]
@Mayank77maruti please tell me what is the progress (Contact in discord) else you will be removed from the issue

**Comment by Mayank77maruti** [comment]
Hey @asmit203 , sorry for getting late i am making the pr asap.

**Comment by asmit203** [comment]
Done
