### ISSUE TITLE
404 page missing

### ISSUE THREAD

**Issue by Yash-Ainapure** [asmit203/TalkitOut#69]
I would like to add a "404 page not found" page . If the redirect url is not present then this page will be shown instead of showing errors on page which is not good for user experience
@asmit203 
the page i am talking about will look like this :

![Screenshot (127)](https://github.com/asmit203/TalkitOut/assets/136250383/b813f2ef-b6eb-482a-ae8f-ffe806ea5eb9)

**Comment by asmit203** [comment]
<img width="336" alt="image" src="https://github.com/asmit203/TalkitOut/assets/92667287/34cd0743-bcd0-4556-ab2b-cad6019fe8a8">
where do you want to go I mean what is the link you click 
provide me the step to reproduce this

**Comment by Yash-Ainapure** [comment]
> <img width="336" alt="image" src="https://github.com/asmit203/TalkitOut/assets/92667287/34cd0743-bcd0-4556-ab2b-cad6019fe8a8">
> where do you want to go I mean what is the link you click 
> provide me the step to reproduce this

If some redirect mismatch problem occurs then this page will be shown instead of showing erros to user (showing errors to user is not good) . This will make user experience better.

**Comment by asmit203** [comment]
ook do you want to get this isssue?

**Comment by Yash-Ainapure** [comment]
> ook do you want to get this isssue?

Yes, and i think it's a  medium issue 🙂

**Comment by asmit203** [comment]
> > ook do you want to get this isssue?
> 
> Yes, and i think it's a medium issue 🙂

ah I really dont think so
